inherit_from: .rubocop_todo.yml
require:
   - rubocop-rails
   - rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/**'
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/**'
    - 'app/controllers/api/**/**'
    - 'config/**/**'
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Max: 6
Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'
    - 'config/**/**'
Lint/MissingSuper:
  Enabled: false
