inherit_from: .rubocop_todo.yml
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/**'
    - 'db/schema.rb'
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/**'
