version: "3.3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: druzhba-rabbitmq
    expose:
      - 5672
    ports:
      - "15672:15672"
      - "5672:5672"
#  vault:
#    image: vault:1.6.7
#    volumes:
#      - .:/vault
#    expose:
#      - 8200
#    ports:
#      - "8200:8200"
#    environment:
#      SKIP_SETCAP: 1
#      VAULT_TOKEN: changeme
#      VAULT_DEV_ROOT_TOKEN_ID: changeme
#      VAULT_ADDR: http://vault:8200
  backend:
    build: .
    volumes:
      - .:/druzhba_rails
    ports:
      - "9771:9771"
    depends_on:
      - db
      - rabbitmq
#      - vault
    environment:
      DRUZHBA_DATABASE_HOST: db
      DRUZHBA_DATABASE_USERNAME: postgres
      DRUZHBA_DATABASE_PASSWORD: password
      DRUZHBA_RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      DRUZHBA_SECRET_KEY_BASE: test
      RAILS_ROOT: /druzhba_rails
      RAILS_ENV: production
      VAULT_TOKEN: changeme
      VAULT_ADDR: http://vault:8200
      RAILS_SERVE_STATIC_FILES: 'true'