version: "3.3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: druzhba-rabbitmq
    expose:
      - 5672
    ports:
      - "15672:15672"
      - "5672:5672"
  backend:
    build: .
    volumes:
      - .:/druzhba_rails
    ports:
      - "9771:3000"
    depends_on:
      - db
      - rabbitmq
    environment:
      DRUZHBA_DATABASE_HOST: db
      DRUZHBA_DATABASE_USERNAME: postgres
      DRUZHBA_DATABASE_PASSWORD: password
      DRUZHBA_RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      DRUZHBA_SECRET_KEY_BASE: test
      RAILS_ROOT: /druzhba_rails