connect: <%= ENV.fetch('DRUZHBA_RABBITMQ_URL', 'amqp://guest:guest@localhost:5672') %>

exchange:
  druzhba:
    name: default
    type: fanout

binding:
  blockchain_events:
    exchange: druzhba
    queue: druzhba-events
    durable: true
    type: fanout

channel:
  druzhba:
    prefetch: 10
