connect: amqp://guest:guest@localhost:5672

exchange:
  druzhba:
    name: default
    type: direct

binding:
  blockchain_events:
    exchange: druzhba
    queue: druzhba-events
    durable: true
    type: direct

channel:
  druzhba:
    prefetch: 10
